In [45]:
import pandas as pd #pandas is a library user for data set manipulation

In [51]:
dataset=pd.read_csv("salaries.csv")#read input file using pandas read function

In [53]:
dataset#display stored dataset in the variable

    years_of_experience  salary
0                   5.0    3150
1                   9.0    3787
2                   4.1    2991
3                  10.0    4551
4                   8.0    3540
5                   1.5    2559
6                   6.1    3269
7                   3.5    2767
8                   3.0    2632
9                   1.0    2237
10                  7.0    3281
11                  8.6    3940
12                  7.4    3467
13                 10.4    4708
14                  1.2    2328
15                  9.3    4109
16                  4.4    3286
17                  7.9    3952
18                  5.6    3417
19                  8.3    3638
20                  6.1    3289
21                  2.3    2698
22                  3.2    2669
23                  6.0    3253
24                  2.0    2526
25                  4.0    2922
26                  7.6    3638
27                 11.0    5034
28                 11.6    5459
29                 12.4    6345

In [63]:
Independent=dataset[["years_of_experience"]]#split input from dataset

In [65]:
dependent=dataset[["salary"]]#split ouput from dataset

In [67]:
Independent#display input dataset

    years_of_experience
0                   5.0
1                   9.0
2                   4.1
3                  10.0
4                   8.0
5                   1.5
6                   6.1
7                   3.5
8                   3.0
9                   1.0
10                  7.0
11                  8.6
12                  7.4
13                 10.4
14                  1.2
15                  9.3
16                  4.4
17                  7.9
18                  5.6
19                  8.3
20                  6.1
21                  2.3
22                  3.2
23                  6.0
24                  2.0
25                  4.0
26                  7.6
27                 11.0
28                 11.6
29                 12.4

In [69]:
dependent#display ouput dataset

    salary
0     3150
1     3787
2     2991
3     4551
4     3540
5     2559
6     3269
7     2767
8     2632
9     2237
10    3281
11    3940
12    3467
13    4708
14    2328
15    4109
16    3286
17    3952
18    3417
19    3638
20    3289
21    2698
22    2669
23    3253
24    2526
25    2922
26    3638
27    5034
28    5459
29    6345

In [73]:
from sklearn.model_selection import train_test_split#import split test and traing dataset function using sklearn library

In [75]:
train_test_split(Independent,dependent,test_size=0.30,random_state=0)#split test and traing dataset using function

[    years_of_experience
 22                  3.2
 5                   1.5
 16                  4.4
 8                   3.0
 14                  1.2
 23                  6.0
 20                  6.1
 1                   9.0
 29                 12.4
 6                   6.1
 4                   8.0
 18                  5.6
 19                  8.3
 9                   1.0
 7                   3.5
 25                  4.0
 3                  10.0
 0                   5.0
 21                  2.3
 15                  9.3
 12                  7.4,
     years_of_experience
 2                   4.1
 28                 11.6
 13                 10.4
 10                  7.0
 26                  7.6
 24                  2.0
 27                 11.0
 11                  8.6
 17                  7.9,
     salary
 22    2669
 5     2559
 16    3286
 8     2632
 14    2328
 23    3253
 20    3289
 1     3787
 29    6345
 6     3269
 4     3540
 18    3417
 19    3638
 9     2237
 7     2767
 25    2922
 3     4551
 0     3150
 21    2698
 15    4109
 12    3467,
     salary
 2     2991
 28    5459
 13    4708
 10    3281
 26    3638
 24    2526
 27    5034
 11    3940
 17    3952]

In [77]:
x_train,x_test,y_train,y_test=train_test_split(Independent,dependent,test_size=0.30,random_state=0)#assign splitted test and train dataset to diff variables

In [83]:
x_train#display input training dataset

    years_of_experience
22                  3.2
5                   1.5
16                  4.4
8                   3.0
14                  1.2
23                  6.0
20                  6.1
1                   9.0
29                 12.4
6                   6.1
4                   8.0
18                  5.6
19                  8.3
9                   1.0
7                   3.5
25                  4.0
3                  10.0
0                   5.0
21                  2.3
15                  9.3
12                  7.4

In [85]:
y_test#display output test dataset

    salary
2     2991
28    5459
13    4708
10    3281
26    3638
24    2526
27    5034
11    3940
17    3952

In [87]:
#model creation
from sklearn.linear_model import LinearRegression#import linearRegression class
regressor=LinearRegression()#assign class to variable
regressor.fit(x_train,y_train)#training the model using train dataset

LinearRegression()

In [89]:
#display the weight
weight=regressor.coef_
weight

array([[262.99824782]])

In [91]:
#display the bias
bias=regressor.intercept_
bias

array([1860.1574062])

In [93]:
#test the created model
y_pred=regressor.predict(x_test)#assign the predicted output to variable

In [95]:
from sklearn.metrics import r2_score#Evaluate the model using R2

In [97]:
r_score=r2_score(y_test,y_pred)#passing arguments as predited and actual output r2 function for Evaluatation
r_score#display r2 value

0.9105069409836487

In [103]:
#save the best model
import pickle#library to convert object to bites and save that in file
filename="finalized_linear.sav"#create a empty file

In [105]:
pickle.dump(regressor,open(filename,'wb'))#write all functions of regressor into newly created file

In [107]:
#load the saved model
loaded_model=pickle.load(open(filename,'rb'))
result=loaded_model.predict([[17]])

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [109]:
result#final output

array([[6331.12761921]])